#!/bin/bash

output_file="page.html"
src_dir="lab04_raw_files"
thumb_dir="thumbnails"
template_begin="template_begin.html"
template_middle="template_middle.html"
template_end="template_end.html"

# Create thumbnails for the pictures and pdf files in the "files" directory
./make_thumbnails
thumbnails_exit_code=$?

if [ $thumbnails_exit_code -ne 0 ]; then
    echo "An error occurred in make_thumbnails. Exiting..."
    exit $thumbnails_exit_code
fi

# Ensure the middle content file is empty before starting
> "$template_middle"

# Start the HTML section for images
echo -e "<article class=\"container article\">\n<div class=\"row\">\n<div class=\"col-md-10 col-md-pull-3 col-md-offset-4 article__content\">\n<div><div><h2>Découvrez-nous en images</h2></div></div>\n<div class=\"row\">" >> "$template_middle"

# Loop through the source directory images
for file in "$src_dir"/*.{jpg,png}; do
    filename=$(basename "$file")
    thumbnail="${thumb_dir}/${filename%.*}_thumb.${filename##*.}"
    if [ -e "$thumbnail" ]; then
        echo -e "<div class=\"col-md-6 col-xs-12\">\n<a href=\"$file\"><img class=\"vignette\" src=\"$thumbnail\" /></a>\n</div>" >> "$template_middle"
    fi
done

# Close the section for images
echo -e "</div>\n</div>\n</div>" >> "$template_middle"

# Start the section for PDFs
echo -e "<div class=\"row\" style=\"margin-top: 40px;\">\n<div class=\"col-md-10 col-md-pull-3 col-md-offset-4 article__content\">\n<div><div><h2>Téléchargez nos brochures</h2></div></div>\n<div class=\"row\">" >> "$template_middle"

# Loop through PDF thumbnails
for file in "$thumb_dir"/*_thumb.*; do
    filename=$(basename "$file")
    pdf="${src_dir}/${filename%_thumb.png}.pdf"
    # Check if the thumbnail corresponds to a PDF file
    if [ -e "$pdf" ]; then
        # Create HTML for the PDF thumbnail linking to the PDF file
        echo -e "<div class=\"col-md-6 col-xs-12\">\n<a href=\"$pdf\"><img class=\"vignette\" src=\"$file\" /></a>\n</div>" >> "$template_middle"
    fi
done

# Close the section for PDFs
echo -e "</div>\n</div>\n</div>\n</article>\n" >> "$template_middle"

# Concat the beginning, middle and end template, then write to the page.html file
cat "$template_begin" "$template_middle" "$template_end" > "$output_file"

rm "$template_middle"
