#!/bin/bash

# Chemin vers le répertoire contenant les images
DIRECTORY="./lab04_raw_files"

# Extension des fichiers à traiter
declare -a EXTENSIONS=("jpg" "jpeg" "png")

# Boucle à travers tous les fichiers dans le répertoire
for IMAGE in $DIRECTORY/*; do
    if [[ -f $IMAGE ]]; then
        # Extraction de l'extension du fichier
        EXTENSION="${IMAGE##*.}"
        EXTENSION="${EXTENSION,,}" # Convertir en minuscules pour la comparaison

        # Vérifier si le fichier est une image
        if [[ " ${EXTENSIONS[@]} " =~ " ${EXTENSION} " ]]; then
            # Obtention des dimensions de l'image avec 'identify'
            DIMENSIONS=$(identify -format ' width: %w, height: %h\n'  "$IMAGE")
            # Affichage du nom du fichier et de ses dimensions
            echo "$(basename "$IMAGE"): $DIMENSIONS"
        fi
    fi
done

